### ISSUE TITLE
Domain filters for locales

### ISSUE THREAD

**Issue by tractorcow** [tractorcow-farm/silverstripe-fluent#43]
Following on from the discussion at #42 fluent needs to be updated to cater for domain switches for locales.

I think the most important thing is that it's easy to configure and use. I propose a config schema similar to the below:

``` yaml

---
Name: myfluentconfig
After: '#fluentconfig'

---
Fluent:
  domains:
    us.domain.com:
      locales:
        - 'en_US'
        - 'es_US'
      default_locale: 'en_US'
    oceania.domain.com:
      locales:
        - 'en_NZ'
        - 'en_AU'
      default_locale: 'en_NZ'
    ca.domain.com:
      locales:
        - 'en_CA'
    www.domain.fr:
      locales:
        - 'fr_FR'
```

I considered allowing the baseURL prefix (E.g. /en_NZ/) to be omitted for domains with only a single locale, but I think a better solution (and referring to #42 above) is to not require the prefix for the home page for the default locale on any domain. This has the added benefit of removing a redirect when landing on the domain home page.

The home pages for each locale would be:
- us.domain.com
- us.domain.com/es_US
- oceania.domain.com
- oceania.domain.com/en_AU
- www.domain.fr

Considering that it can be difficult to work with live configurations in the main yaml configuration file (especially when testing locally) I imagine that the routing scheme would only be active when the current domain was one of the customised domains (so running off localhost would not trigger the switch).

Any comments on this?
