### ISSUE TITLE
BUG?: frontend_publish_required cannot be configured for child classes

### ISSUE THREAD

**Issue by chrispenny** [tractorcow-farm/silverstripe-fluent#490]
It could be argued that this is an "improvement", if this was not originally the intended purpose.

## The issue

By default, we are applying `frontend_publish_required` to `DataObject`:
```yml
---
Name: fluentmodel
---
SilverStripe\ORM\DataObject:
  frontend_publish_required: true
```

This works fine.

Lets say that you decide you want **all** of your pages to not require publishing. You might do something like:
```yml
---
Name: my_fluentmodel
After: fluentmodel
---
SilverStripe\CMS\Model\SiteTree:
  frontend_publish_required: false
```

This also works fine.

But, now let's say that you only want a specific page type to not require publishing (`MyPage extends SiteTree`). **Instead of using the above config applied to `SiteTree`**, you might do something more specific, like targeting one of your page Classes:

```yml
---
Name: my_fluentmodel
After: fluentmodel
---
App\Page\MyPage:
  frontend_publish_required: false
```

This does not appear to work.

## Investigation

Apologies that this is not being as in depth as usual. We're really in "crunch time" at the moment.

I added a quick debug to the `requireSavedInLocale()` method:
```php
protected function requireSavedInLocale()
{
    // Filter is disabled in CMS
    if (!FluentState::singleton()->getIsFrontend()) {
        return false;
    }

    Debug::message($this->owner->ClassName);
    Debug::message($this->owner->config()->get('frontend_publish_required'));
    return $this->owner->config()->get('frontend_publish_required');
}
```

The output of this when visiting a `MyPage` record was:
```
Debug (line 954 of FluentExtension.php): SilverStripe\CMS\Model\SiteTree
Debug (line 955 of FluentExtension.php): 1

Debug (line 954 of FluentExtension.php): SilverStripe\CMS\Model\SiteTree
Debug (line 955 of FluentExtension.php): 1

Debug (line 954 of FluentExtension.php): SilverStripe\CMS\Model\SiteTree
Debug (line 955 of FluentExtension.php): 1

Debug (line 954 of FluentExtension.php): SilverStripe\ErrorPage\ErrorPage
Debug (line 955 of FluentExtension.php): 1

The requested page could not be found.
```

Cheers, team!
