### ISSUE TITLE
Root / cannot redirect to /locale/ with config

### ISSUE THREAD

**Issue by JorisDebonnet** [tractorcow-farm/silverstripe-fluent#674]
I'm on 5.0.0 and have the following explicit config: 
```yml
TractorCow\Fluent\Extension\FluentDirectorExtension:
  detect_locale: true
  disable_default_prefix: false
```
I know the latter config value is actually the default. 

What is working well: 
- Upon visiting the website root, the locale is detected based on browser settings (great, thanks to $detect_locale=true)
- When surfing through the subpages, the /urlSegment/ is always there in any locale (great, thanks to $disable_default_prefix=false)

But what I cannot get to work is this: 
- I am expecting visiting the website root to immediately redirect to the /urlSegment/ of the detected locale. That's not happening. Part of the reason I want this is because my client gets confused that visiting (and staying on) the same address can show different locales.

I'm sure I could make this work with custom logic, but is there no config for this?
(Actually I don't know what the $domain_mode config is for; maybe would be useful to expand that phpDoc)
