### ISSUE TITLE
On dev/build: "Table 'ss4_project.Member_Localised' doesn't exist"

### ISSUE THREAD

**Issue by spekulatius** [tractorcow-farm/silverstripe-fluent#725]
Hello @tractorcow and @robbieaverill,

I've got fresh project using SilverStripe 4.8 and fluent 5.0.0. I've added an extension to the Member and the fluent extension with fields to translate:

```yml
SilverStripe\Security\Member:
  extensions:
    - MemberExtension
    - TractorCow\Fluent\Extension\FluentExtension
  translate:
    - ShortDesc
    - Description
```

Seems pretty standard, but I get `Table 'ss4_project.Member_Localised' doesn't exist` during dev/build. I've tried without the translate fields as well as in a different configuration loaded after the member extension. No luck.

I have the feeling I'm missing something obvious.

Any clues are appreciated. Thank you!
