### ISSUE TITLE
Feature request: Locale and Domain confguration outside the DB / better in yml File

### ISSUE THREAD

**Issue by RoyalPulp** [tractorcow-farm/silverstripe-fluent#767]
Hi there :)

As this gets me headaches on every project, my greatest wish:

I think, the configuration of the locales and domains was and would be better in the filesystem than in the Database

Database should be portable from one server to another without breaking the system  (Demo to Live Server for example) 
Also: it is really soooo much faster and sooo much easier to support 

I can write write my configuration files, deploy, and the system is there with the Languages as planned, I can setup a test-Server, just use a slightly modified conf and transfer the production db and vice versa.

I remember the setup from older fluent versions, 

Thanks, have a great day ! :)

**Comment by tractorcow** [comment]
You are right, it's definitely a valid use case to "lock" down the locales etc... via yml.

What you can do, in the mean time, is deny access to the locales section, and replace the entire scaffolding of this via defaultRecords. You can do this via YML too if you know how.


```yaml
TractorCow\Fluent\Model\Locale:
  default_records:
    - Title: 'nz'
      Locale: 'en_NZ'
      URLSegment: 'kiwi'
    - Title: 'au'
      Locale: 'en_AU'
      URLSegment: 'aussie'
```

You can do something similar with locales, but I don't know if you can easily link records in relations with default_records config.
