### ISSUE TITLE
FluentMenuExtension trouble

### ISSUE THREAD

**Issue by oetiker** [tractorcow-farm/silverstripe-fluent#77]
am using the latest 3.1.*-dev fluent and ss 3.1.5. I would like to be able to make some pages only available in certain languages. So I added this to my _config/fluent.yml

``` yaml

---
Name: fluentextensions

---
SiteTree:
  translate:
    - 'Title'
    - 'ShowInMenus'
    - 'MenuTitle'
    - 'Content'
    - 'URLSegment'
    - 'MetaDescription'
    - 'CustomMetaTags'
  extensions:
    - 'FluentSiteTree'
    - 'FluentMenuExtension'
```

after /dev/build, the cms ui looks good, BUT
the pages do not show up in the website at all anymore

I bet I am missing something. Any hints ?
