### ISSUE TITLE
HomepageLink with the $AbsoluteBaseURL template variable

### ISSUE THREAD

**Issue by achappard** [tractorcow-farm/silverstripe-fluent#792]
Hello,
I installed Silverstripe 4.12.3 with Silverstripe-Fluent in version 6.0.0. I then configured two languages (fr_FR which is global) and en_US.

In my main layout I try to make a link to the home page with the variable $AbsoluteBaseURL. This link from the fr_FR language is well www.monsite.com. However, if I go to www.monsite.com/en the link to the home page remains www.monsite.com. It should be www.monsite.com/en right?

The only configuration I made is

```
---
Name: myfluentconfig
---
TractorCow\Fluent\Extension\FluentDirectorExtension:
  disable_default_prefix: true
```

I think I need to configure Fluent or else Silverstripe but I can't find any documentation about it. Can you help me please?

**Comment by tractorcow** [comment]
If you are looking for docs, check the https://github.com/tractorcow-farm/silverstripe-fluent/blob/4/docs/en/configuration.md (and other files in that folder).

Can you verify that fr_FR is set as the global default, and not en ?

**Comment by achappard** [comment]
Yes, I checked that as you can see in the attached image. It's really weird.

<img width="319" alt="fluent" src="https://user-images.githubusercontent.com/13727324/231081649-8ce4e9e0-104e-4adb-b11d-edc181d48d1e.png">

**Comment by tractorcow** [comment]
It's possible that it's using en if you have locale detection turned on. i.e. it's using your browser headers to pick the locale, and not the locale prefix.

I believe in fluent 5 we might have changed that behaviour (turned it off).

**Comment by achappard** [comment]
Thanks for your investigation @tractorcow but the problem is still there. I reinstalled SS in version 4.12.0, Silverstripe Fluent in version 6.0.0. Here is my configuration file : `app/_config/fluent.yml`

```
---
Name: myfluentconfig
---
TractorCow\Fluent\Extension\FluentDirectorExtension:
  disable_default_prefix: false
  detect_locale: false

TractorCow\Fluent\Model\Locale:
  default_records:
    fr:
      Title: Français
      Locale: fr_FR
      URLSegment: fr
      IsGlobalDefault: 1
      Sort: 1
    en:
      Title: Anglais
      Locale: en_US
      URLSegment: en
      IsGlobalDefault: O
      Sort: 2
```

And when I browse the English version of the site, the link that points to the home page takes me to the French version of the home page. Here is the template code:

```
<a href="$AbsoluteBaseURL">
    <%t TemplateString.HomePageReturn "Retour à l'accueil" %>
</a>
```
