### ISSUE TITLE
Fluent breaks silverstrip's fulltext filter (not SearchForm!)

### ISSUE THREAD

**Issue by sirtoobii** [tractorcow-farm/silverstripe-fluent#797]
When using the `Fulltext` filter as documented [here](https://docs.silverstripe.org/en/4/developer_guides/search/fulltextsearch/#fulltext-filter), Fluent augments the query with `COALESCE` which is not compatible with the `MATCH`, `AGAINST` syntax.

## Steps to reproduce
- Create a locale in the CMS backend
- Add a Fulltext index in `Content` and `Title`:
```yaml
SilverStripe\CMS\Model\SiteTree:
  indexes:
    FullTextSearch:
      type: fulltext
      columns: ['Title', 'Content']
```
- Setup a dummy controller:
```php
<?php

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Control\Controller;

class TestController extends Controller
{
    public function index($request) {
        $query = $this->getRequest()->getVar('q');
        return SiteTree::get()->filter('FullTextSearch:Fulltext', $query)->first()->Title;
    }

}
```
- Add route:
```yaml
SilverStripe\Control\Director:
  rules:
    'search/': 'TestController'
```
- Run a search query: `http://localhost:8474/search?q=silverstripe`
