### ISSUE TITLE
Can't create FluentFilteredExtension

### ISSUE THREAD

**Issue by SewerHrehorowicz** [tractorcow-farm/silverstripe-fluent#85]
It causes following error:
PHP Fatal error:  collateDataFields() I noticed that a field called 'LocaleFilter_en_US' appears twice in your form: '(unknown form)'.  One is a 'CheckboxField' and the other is a 'CheckboxField'

I have no clue what causes it, I followed instructions, and module seems to be working except that. In my config looks like that:

```

---
Name: contentsectionsconfig

---
ContentSection:
  extensions:
    - 'FluentExtension'
    - 'FluentFilteredExtension'
  translate:
    - 'Title'
    - 'Content'
```
