### ISSUE TITLE
Data objects not publishing

### ISSUE THREAD

**Issue by jesscostello** [tractorcow-farm/silverstripe-fluent#853]
### Module version(s) affected

7.1.1

### Description

I have a dataobject which has the versioned extension (versioning only, no staging) and FluentVersionedExtension applied. No matter how I create/save the object it always seems to remain in draft format. I have simplified down my dataobject for the purposes of replication and to rule out anything from the class itself but am still seeing issues. Not sure if this is definitely a bug or if I'm missing something 

### How to reproduce

Using Silverstripe 5.2

<details><summary>PHP Class</summary>
<p>

```php
<?php

namespace Name\Website\Models;

use SilverStripe\AssetAdmin\Forms\UploadField;
use SilverStripe\Assets\Image;
use SilverStripe\LinkField\Models\Link;
use SilverStripe\ORM\DataObject;

class TestObject extends DataObject
{
    private static $table_name = 'TestObject';

    private static $db = [
        'Name' => 'Varchar(255)',
    ];

    private static $has_one = [
        'PhoneLink' => Link::class,
    ];

    private static $many_many = [
        'Images' => Image::class,
    ];

    private static $owns = [
        'Images',
        'PhoneLink',
    ];

    private static $cascade_duplicates = [
        'Images',
        'PhoneLink',
    ];

    private static $cascade_deletes = [
        'Images',
        'PhoneLink',
    ];

    public function getCMSFields()
    {
        $this->beforeUpdateCMSFields(
            function ($fields) {
                $fields->removeByName(['Images']);
                $uploadField = UploadField::create('Images')
                    ->setAllowedExtensions(['png', 'jpg', 'jpeg'])
                    ->setIsMultiUpload(true);

                $fields->addFieldToTab(
                    'Root.Main',
                    $uploadField,
                );
            }
        );
        return parent::getCMSFields();
    }
}

```

</p>
</details> 

<details><summary>YML Config</summary>
<p>
File 1

```yml
---
Name: app-config
---
TPNT\Website\Models\TestObject:
  extensions:
    - SilverStripe\Versioned\Versioned.versioned
```

File 2 
```yml
---
Name: fluent-config
After:
  - '#app-config'
  - '#versionedfiles'
---
TractorCow\Fluent\Model\Locale:
  default_records:
    en:
      Title: English
      Locale: en_NZ
      URLSegment: en
      IsGlobalDefault: 1
    mi:
      Title: Te Reo Māori
      Locale: mi_NZ
      URLSegment: mi

TractorCow\Fluent\Extension\FluentExtension:
  frontend_publish_required: any

SilverStripe\LinkField\Models\Link:
  extensions:
    - TractorCow\Fluent\Extension\FluentVersionedExtension

Name\Website\Models\TestObject:
  extensions:
    - TractorCow\Fluent\Extension\FluentVersionedExtension
```
</p>
</details> 

When first creating an object there is only a create button, clicking this results in the following 
![Screenshot 2024-05-24 at 8 57 56 AM](https://github.com/tractorcow-farm/silverstripe-fluent/assets/33467471/ba3f8d2b-817b-49cc-b0c4-763c5c70f261)

It also does not publish the image as I would expect (Image relationship appears in $owns).

I then have the localisation menu and click 'save and publish (all locales)'. This does publish the image but not the object

![Screenshot 2024-05-24 at 8 58 24 AM](https://github.com/tractorcow-farm/silverstripe-fluent/assets/33467471/4e25e82a-a6a4-44fa-a97e-4563f86bd67e)

Clicking 'publish in this locale' in the localisation table also does not publish and leaves the record in draft state. 

Any help would be much appreciated!
